# Generated by Django 4.1.4 on 2022-12-21 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0.0)),
                ('fecha_pago', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servis', to='servis.servis')),
            ],
        ),
        migrations.CreateModel(
            name='Pagito_expirado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagis.pagito')),
            ],
        ),
    ]
